 <div class="footer-top">
      <div class="footer-section">
        <a href="home.php"><h4>Fashion House</h4></a>
        <p>Shop through trends</p>
      </div>
      <div class="footer-section">
        <a href="about.php"><h4>About Us</h4></a>
        <div class="social-icons">
          <a href="https://www.instagram.com/" target="_blank"><img class="instagram" src="icons/instagram.svg" alt="instagram logo"></i></a>
          <a href="https://www.facebook.com/" target="_blank"><img class="facebook" src="icons/facebook.svg" alt="facebook logo"></i></a>
          <a href="https://x.com/?lang=en" target="_blank"><img class="x" src="icons/x.svg" alt="x logo"></i></a>
        </div>
      </div>
      <div class="footer-section">
        <a href="help.php"><h4>Help</h4></a>
        <ul>
          <li>Contact us at :<br><a href="mailto:fashionhouse@gmail.com">fashionhouse@gmail.com</a></li>
          <li><a href="help.php">Help Center</a></li>
          <li><a href="">Privacy Policies</a></li>
          <li><a href="">Terms and Conditions</a></li>
        </ul>
      </div>
    </div>
    <div class="footer-bottom">
      &copy; fashionhouse.com
    </div>