 <div class="footer-top">  

  <!-- Brand Section -->
  <div class="footer-section">
    <a href="home.php" class="footer-blue">
      <h4>Fashion House</h4>
    </a>
    <p>Shop through trends</p>
  </div>

  <!-- About + Social Icons -->
  <div class="footer-section">
    <a href="about.php" class="footer-blue">
      <h4>About Us</h4>
    </a>

    <div class="social-icons">
      <a href="https://www.instagram.com/" target="_blank">
        <img class="instagram" src="icons/instagram.svg" alt="instagram logo">
      </a>

      <a href="https://www.facebook.com/" target="_blank">
        <img class="facebook" src="icons/facebook.svg" alt="facebook logo">
      </a>

      <a href="https://x.com/?lang=en" target="_blank">
        <img class="x" src="icons/x.svg" alt="x logo">
      </a>
    </div>
  </div>

  <!-- Help Section -->
  <div class="footer-section">
    <a href="help.php" class="footer-blue">
      <h4>Help</h4>
    </a>

    <ul>
      <li>
        Contact us at:<br>
        <a href="mailto:fashionhouse@gmail.com" class="footer-blue">
          fashionhouse@gmail.com
        </a>
      </li>

      <li>
        <a href="help.php" class="footer-blue">Help Center</a>
      </li>

      <li>
        <a href="#" class="footer-blue">Privacy Policies</a>
      </li>

      <li>
        <a href="#" class="footer-blue">Terms and Conditions</a>
      </li>
    </ul>
  </div>

</div>

<div class="footer-bottom">
  &copy; fashionhouse.com
</div>

